### ISSUE TITLE
Manage Palette - palette won't update

### ISSUE THREAD

**Issue by seaverd** [node-red/node-red-docker#332]
### Current Behavior

I have several palettes that indicate they have updates available.  Also same error occurs when attempting to install a new palette. 
 When I attempt to update/install them after a few seconds, I get the message below in the logs:

PLEASE NOTE:  I rolled back my docker tag to 3.0.1 and all functions as it is supposed to and I don't get the error below.  The errors below happen with docker tag 3.0.1-1 and 3.0.2 latest.

```
51 verbose type system
52 verbose stack FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/node-red-contrib-power-monitor: ENOSYS: function not implemented, link '/data/.npm/_cacache/tmp/536b9d89' -> '/data/.npm/_cacache/content-v2/sha512/ca/78/ecf9ea9e429677649e945a71808de04bdb7c3b007549b9a2b8c1e2f24153a034816fdb11649d9265afe902d0c1d845c02ac702ae46967c08ebb58bc2ca53'
52 verbose stack at /usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:168:15
52 verbose stack at async RegistryFetcher.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:99:25)
52 verbose stack at async RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:124:23)
52 verbose stack at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1108:19)
52 verbose stack at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:976:11)
52 verbose stack at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
52 verbose stack at async Promise.all (index 1)
52 verbose stack at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
52 verbose stack at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:156:5)
52 verbose stack at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
53 verbose cwd /data
54 verbose Linux 5.15.46-Unraid
55 verbose node v16.16.0
56 verbose npm v8.11.0
57 error code ENOSYS
58 error syscall link
59 error path /data/.npm/_cacache/tmp/536b9d89
60 error dest /data/.npm/_cacache/content-v2/sha512/ca/78/ecf9ea9e429677649e945a71808de04bdb7c3b007549b9a2b8c1e2f24153a034816fdb11649d9265afe902d0c1d845c02ac702ae46967c08ebb58bc2ca53
61 error errno ENOSYS
62 error Invalid response body while trying to fetch https://registry.npmjs.org/node-red-contrib-power-monitor: ENOSYS: function not implemented, link '/data/.npm/_cacache/tmp/536b9d89' -> '/data/.npm/_cacache/content-v2/sha512/ca/78/ecf9ea9e429677649e945a71808de04bdb7c3b007549b9a2b8c1e2f24153a034816fdb11649d9265afe902d0c1d845c02ac702ae46967c08ebb58bc2ca53'
63 verbose exit 1
64 timing npm Completed in 3896ms
65 verbose unfinished npm timer reify 1661012682451
66 verbose unfinished npm timer reify:loadTrees 1661012682455
67 verbose code 1
68 error A complete log of this run can be found in:
68 error /data/.npm/_logs/2022-08-20T16_24_42_307Z-debug-0.log
```

### Expected Behavior

Update/install without errors.  Rolling back to 3.0.1 solves my issue.

### Steps To Reproduce

Just have 3.0.1-1 or later nodered installed and attempt to install palette or update palette.

### Example flow

```
paste your flow here
```
Not required

### Environment

- Node-RED version: 3.0.1-1 and later
- Node.js version: v16.16.0
- npm version: 8.11.0
- Platform/OS: Linux 5.15.46-Unraid
- Browser: Chrome

**Comment by hardillb** [comment]
@seaverd moved (the old URL should redirect anyway)

**Comment by fuzzy01** [comment]
Solution is to enable hard links in Unraid.

Go to Settings -> Global Share Settings -> Tunable (support hard links) and set it to Yes.
